name: Matomo Tests

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - '**.x-dev'
      - 'next_release'
  workflow_dispatch:

permissions:
  actions: read
  checks: none
  contents: read
  deployments: none
  issues: read
  packages: none
  pull-requests: read
  repository-projects: none
  security-events: none
  statuses: none
concurrency:
  group: php-${{ github.ref }}
  cancel-in-progress: true

jobs:
  PHP:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        command: [ 'UnitTests', 'SystemTestsPlugins' ,'SystemTestsCore' , 'IntegrationTestsCore', 'IntegrationTestsPlugins' ]
        type: [ 'PHP' ]
        php: [ '7.2', '8.1' ]
        adapter: [ 'PDO_MYSQL', 'MYSQLI' ]
        exclude:
          - php: '8.1'
            adapter: 'PDO_MYSQL'
          - php: '7.2'
            adapter: 'MYSQLI'
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          persist-credentials: false
          submodules: true
      - name: running tests
        uses: matomo-org/github-action-tests@main
        with:
          test-type: ${{ matrix.type }}
          mysql-driver: ${{ matrix.adapter }}
          php-version: ${{ matrix.php }}
          test-command: ${{ matrix.command }}
          redis-service: true

  Javascript:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          persist-credentials: false
          submodules: true
      - name: running tests
        uses: matomo-org/github-action-tests@main
        with:
          test-type: 'JS'
          php-version: '7.2'
          node-version: '12'

  Angular:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: false
          persist-credentials: false
          submodules: true
      - name: running tests
        uses: matomo-org/github-action-tests@main
        with:
          test-type: 'Angular'
          node-version: '16'
          test-command: ${{ matrix.tests }}
          mysql-service: false

  UI:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        parts: [ 0,1,2 ]
    steps:
      - uses: actions/checkout@v3
        with:
          lfs: true
          persist-credentials: false
          submodules: true
      - name: running tests
        uses: matomo-org/github-action-tests@main
        with:
          test-type: 'UI'
          php-version: '7.2'
          test-command: ${{ matrix.parts }}
          node-version: '16'
          artifact-pass: ${{ secrets.ARTIFACTS_PASS }}
          php-memory: "-1"
          redis-service: true

